---
title: "BH_weather"
output: pdf_document
date: "2023-02-08"
---

## Import Datasets
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotrix)
results <- read.csv("p-values_used_correlation_weather.csv")
set.seed(0)
df <- read.csv("trimmed_df_weather.csv")
```

## Run BH
```{r djsak}
#get p values
P <- results$p_values

#set alpha = 0.1
alpha = 0.1
BH_thres <- (1:length(results$p_values))*alpha/length(results$p_values)
sorted_idx <- order(P)
cutoff <- max(which(P[sorted_idx]<BH_thres))-1
idx_rej_BH <- sorted_idx[1:cutoff]
```

```{r}
idx_rej_BH
```

```{r dajskdal}
selected_routes <- results[idx_rej_BH,]
selected_routes
```

## Run Storey BH
```{r s-bh}
Storey_BH <- function(P,alpha,gamma){
  pi_0_hat <- (sum(P>gamma))/(length(P)*(1-gamma))
  Storey_thres <- (1:length(P))*alpha/(length(P)*pi_0_hat)
  sorted_idx <- order(P)
  cutoff <- max(which(P[sorted_idx]<Storey_thres))
  idx_rej <- sorted_idx[1:cutoff]
  idx_rej
}

idx_rej_SBH <- Storey_BH(P, 0.1, 0.5)
idx_rej_SBH
```

## Select the Routes by Storey BH
```{r sbh}
selected_routes_SBH <- results[idx_rej_SBH,]
selected_routes_SBH
```